app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register_organizer, name='register'),
    # path('register-organizer/', views.register_organizer, name='register_organizer'),
    path('adminpage/', views.admin, name='adminpage'),
    path('organizer/', views.organizer, name='organizer'),
    path('participant/', views.participant, name='participant'),
    path('register-admin/', views.registeradmin, name='registeradmin'),  # Use hyphen for consistency
]

trial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('app.urls')),
]

app/models.py
import json
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    is_admin = models.BooleanField('Is admin', default=False)
    is_organizer = models.BooleanField('Is organizer', default=False)
    is_participant = models.BooleanField('Is participant', default=False)
    event = models.CharField(max_length=50, default="", blank=True, null=True)
    event_list_user  = models.CharField(max_length=50, default="", blank=True, null=True)


class Event(models.Model):
    event_list = models.CharField(max_length=100,default="", blank=True, null=True)
    
    def __str__(self):
        return self.event_list

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User,Event

class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

class SignupForm(UserCreationForm):
    ROLES = [
        ('admin', 'Admin'),
        ('organizer', 'Organizer'),
        ('participant', 'Participant'),
    ]

    EVENTS = [
        ('singing', 'Singing'),
        ('dancing', 'Dancing'),
        # Add more events as needed
    ]

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
   
    user_role = forms.ChoiceField(choices=ROLES, required=True, label='Select Role', widget=forms.Select(attrs={"class": "form-control"}))
    event = forms.ModelChoiceField(queryset=Event.objects.all(), required=False, empty_label="Select Event", label='Select Event', widget=forms.Select(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'user_role', 'event',"event_list_user")
 


class EventForm(forms.ModelForm):
    event_list = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = Event
        fields = ("event_list",)

app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import SignupForm, LoginForm,EventForm
from .models import User

def index(request):
    return render(request, 'index.html')

def register(request):
    return render(request, 'register.html')

def register_organizer(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        event_form = EventForm(request.POST)
        if form.is_valid() and event_form.is_valid():
            user = form.save(commit=False)
            user.is_admin = form.cleaned_data['user_role'] == 'admin'
            user.is_organizer = form.cleaned_data['user_role'] == 'organizer'
            user.is_participant = form.cleaned_data['user_role'] == 'participant'
            user.event = form.cleaned_data['event']
            user.event_list_user = event_form.cleaned_data['event_list']
            user.save()

            event = event_form.save(commit=True)
            event.user = user
            event.event_list = event_form.cleaned_data['event_list']  # Access 'event_list' from the event_form
            event.save()

            return redirect('login_view')  # Replace 'login_view' with your login page URL or name
    else:
        form = SignupForm()
        event_form = EventForm()

    return render(request, 'register.html', {'form': form, 'event_form': event_form})
def registeradmin(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            admin = form.save(commit=False)
            admin.is_admin = True
            admin.save()
            return redirect('login_view')
    else:
        form = SignupForm()

    return render(request, 'register.html', {'form': form})

def login_view(request):
    form = LoginForm(request.POST or None)
    msg = None

    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_admin:
                    login(request, user)
                    return redirect('adminpage')
                elif user.is_organizer:
                    login(request, user)
                    return redirect('organizer')
                elif user.is_participant:
                    login(request, user)
                    return redirect('participant')
            else:
                msg = 'Invalid username or password'
        else:
            msg = 'Error validating form'

    return render(request, 'login.html', {'form': form, 'msg': msg})

def admin(request):
    return render(request, 'admin.html')

def organizer(request):
    return render(request, 'organizer.html')

def participant(request):
    return render(request, 'participant.html')

templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin</title>
</head>
<body>
    <h1>Hello! {{user.username}} </h1>
    <h2>you created event: {{user.event_list_user}}</h2>
    
    </ul>

</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home page </title>
</head>
<body>
 <h1> welcome to the home page Mr. Django!!!!!!!!!!</h1>
</body>
</html>

templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">

    <title>Multi-user</title>
  </head>
  <body>
  <div class="content">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-12">
              <div class="form-block">
                  <div class="mb-4">
                      <h1>Welcome </h1>
                  </div>
                  <label>Log in if you already have registered!</label>
                  <div class="form-group last mb-4">
                      <div><button class="btn btn-pill text-light btn-block btn-info"><a href="{% url 'login_view' %}">login</a></button></div>
                  </div>
                  <label>If not, register here!</label>
                  <div class="form-group last mb-4">
                      <div><button class="btn btn-pill text-white btn-block btn-info"><a href="{% url 'register' %}">register</a></button></div>
                  </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  </div>


    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">

    <title>Login</title>
  </head>
  <body>
  <div class="content">
    <div class="container">
      <div class="row justify-content-center">
        <!-- <div class="col-md-6 order-md-2">
          <img src="images/undraw_file_sync_ot38.svg" alt="Image" class="img-fluid">
        </div> -->
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-12">
              <div class="form-block">
                  <div class="mb-4">
                </div>

              <span class="mb-0 text-muted">
                {% if msg %}
                    {{ msg | safe }}
                {% else %}
                    Login page
                {% endif %}
              </span>
                <form  method="post">
                    {% csrf_token %}
                  <div class="form-group first mb-4">
                    <label for="username" id="username-label">Username</label>
                      {{ form.username }}
                  </div>
                  <div class="form-group last mb-4">
                    <label for="password" id="password-label">Password</label>
                    {{ form.password }}
                  </div>

                  {% comment %} <div class="d-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-0"><span class="caption">Remember me</span>
                      <input type="checkbox" checked="checked"/>
                      <div class="control__indicator"></div>
                    </label>
                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                  </div> {% endcomment %}

                  <input type="submit" value="Log In" class="btn btn-pill text-white btn-block btn-primary">
                </form>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  </div>


    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script>
      // Add event listeners to the username and password fields to hide the labels when they have values
      document.addEventListener('DOMContentLoaded', function () {
          var usernameInput = document.getElementById('id_username'); // Assuming 'id_username' is the actual ID of your username input field
          var usernameLabel = document.getElementById('username-label');
          
          var passwordInput = document.getElementById('id_password'); // Assuming 'id_password' is the actual ID of your password input field
          var passwordLabel = document.getElementById('password-label');
  
          function toggleLabelVisibility(input, label) {
              if (input.value.trim() !== '') {
                  label.style.display = 'none';
              } else {
                  label.style.display = 'block';
              }
          }
  
          usernameInput.addEventListener('input', function () {
              toggleLabelVisibility(usernameInput, usernameLabel);
          });
  
          passwordInput.addEventListener('input', function () {
              toggleLabelVisibility(passwordInput, passwordLabel);
          });
      });
  </script>
  </body>
</html>

templates/organizer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Organizer</title>
</head>
<body>
    <h1>Hello! Organizer, {{user.username}} </h1>
    <h2>The events to be held are TechVision, Business Ideas, Photography, Group Discussion and Treasure Hunt</h2>
</body>
</html>

templates/participant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Participant</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">
</head>
<body>
    <h1>Hello! Participant {{user.username}} </h1>
    <h3>You are registered in {{user.event}}</h3>
</body>
</html>

templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts and Stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">

    <title>Register</title>

    <!-- Custom Scripts -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var userRoleField = document.querySelector('#id_user_role');
            var eventlistField = document.querySelector('#eventList');
            var eventField = document.querySelector('#eventField');
    
            function toggleEventField() {
                if (userRoleField.value === 'participant') {
                    eventField.style.display = 'block';
                    eventlistField.style.display ="none";

                }else if(userRoleField.value === 'admin') {
                    eventlistField.style.display ="block";
                    eventField.style.display = 'none';

                }
                else {
                    eventlistField.style.display ="none";
                    eventField.style.display = 'none';
                }
            }
    
            toggleEventField(); // Call initially to set the display based on initial value
    
            userRoleField.addEventListener('change', toggleEventField);
        });
    </script>
</head>

<body>
    <div class="content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="form-block">
                                <span class="mb-0 text">
                                    {% if msg %}
                                    {{ msg | safe }}
                                    {% else %}
                                    Registration page
                                    {% endif %}
                                </span>
                               
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.username.label_tag }} {{ form.username }}
                                    {{ form.email.label_tag }} {{ form.email }}
                                    {{ form.password1.label_tag }} {{ form.password1 }}
                                    {{ form.password2.label_tag }} {{ form.password2 }}
                                    {{ form.user_role.label_tag }} {{ form.user_role }}
                                    
                                    <div id="eventField" style="display: none;">
                                        {{ form.event.label_tag }} {{ form.event }}
                                    </div>
                                    <div id="eventList" style="display: none;">
                                        {{ event_form.event_list.label_tag }} {{ event_form.event_list }}
                                    </div>
                                
                                    <span class="text-error">{{ form.errors }}</span>
                                    <input type="submit" value="Register" class="btn btn-pill text-white btn-block btn-primary">
                                </form>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/register_organizer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts and Stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">

    <title>Register</title>

    <!-- Custom Scripts -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

   
</head>

<body>
    <div class="content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="form-block">
                                <span class="mb-0 text">
                                    {% if msg %}
                                    {{ msg | safe }}
                                    {% else %}
                                    Registration page
                                    {% endif %}
                                </span>
                               
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.username.label_tag }} {{ form.username }}

                                    {{ form.email.label_tag }} {{ form.email }}

                                    {{ form.password1.label_tag }} {{ form.password1 }}

                                    {{ form.password2.label_tag }} {{ form.password2 }}
                                    
                                    {{ form.user_role.label_tag }} {{ form.user_role }}
                                    <div id="id_event_div" {% if form.user_role.value != 'participant' %}style="display: none;"{% endif %}>
                                        {{ form.event.label_tag }} {{ form.event }}
                                    </div>
                                    <span class="text-error">{{ form.errors }}</span>
                                    <input type="submit" value="Register"
                                        class="btn btn-pill text-white btn-block btn-primary">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/register_participant.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts and Stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">

    <title>Register</title>

    <!-- Custom Scripts -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

   
</head>

<body>
    <div class="content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="form-block">
                                <span class="mb-0 text">
                                    {% if msg %}
                                    {{ msg | safe }}
                                    {% else %}
                                    Registration page
                                    {% endif %}
                                </span>
                               
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.username.label_tag }} {{ form.username }}

                                    {{ form.email.label_tag }} {{ form.email }}

                                    {{ form.password1.label_tag }} {{ form.password1 }}

                                    {{ form.password2.label_tag }} {{ form.password2 }}
                                    
                                    {{ form.user_role.label_tag }} {{ form.user_role }}
                                    {{ form.event.label_tag }} {{ form.event }}

                                    <div id="id_event_div" {% if form.user_role.value != 'participant' %}style="display: none;"{% endif %}>
                                        {{ form.event.label_tag }} {{ form.event }}
                                    </div>
                                    <span class="text-error">{{ form.errors }}</span>
                                    <input type="submit" value="Register"
                                        class="btn btn-pill text-white btn-block btn-primary">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>